admins:
- 2043771174
masking:
  users: {}
pairs:
- bidirectional: true
  enabled: true
  filters:
    keywords:
      allow: []
      block:
      - dmm
    types:
      allow:
      - text
      - photo
      - video
      - sticker
      - document
      - voice
      - animation
  group_a_chat_id: -1003746947950
  group_b_chat_id: -1003766457201
  masking:
    a_to_b: {}
    b_to_a: {}
  name: example-pair
